name: Update Git Submodules

on:
  push:
    branches:
      - master  # or any other branch you want the action to trigger on
  workflow_dispatch:

jobs:
  update-submodules:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          submodules: recursive  # This ensures all submodules are checked out recursively

      - name: Update Git submodules
        run: |
          git submodule update --remote --merge
          git add .
          git commit -m "Update submodules to the latest commit" || echo "No changes to commit"

      - name: Push changes
        run: git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
